### ISSUE TITLE
What does null info.json that comes with HTTP 401 look like?

### ISSUE THREAD

**Issue by zimeon** [IIIF/auth#2]
Copying existing discussion:

@jpstroop 4:58 PM Jan 14
Probably info.json-like , but not info.json since, width, height, profile, etc. are required? 
http://iiif.io/api/image/2.0/#image-information
	
@azaroth42 5:00 PM Jan 14
height: 0, width: 0, profile: api/auth/1/no-content.json ?
	
@jpstroop 5:01 PM Jan 14
Or go ahead an report them. Knowing dimensions doesn't help you get the image.
	
@jpstroop 2:39 PM Jan 27
height: null, width: null?

**Comment by zimeon** [comment]
Observations:
  * This is used only with 401 response code and the code already tells us that this is a null info.json, we don't need the content of info.json to do so (but it would be OK if it did)
  * Key requirement will be to pull out the auth'n info which should be the same form as used for 301 response (assume a service profile per http://iiif.io/api/annex/services/)
  * There is only utility in mirroring the rest of a normal info.json if clients will use a generic info.json parser to read the data. I don't have a good sense of this.

Based on the above I see two options:

### 1. Bare service definition

```
{
  "@context": "http://iiif.io/api/image/2/context.json", 
  "service": {
    "@context": "http://iiif.io/auth/2/context.json",
    "auth": "http://go-here-to-auth",
    ...maybe more in here...
  }
}
```

### 2. Minimal image information with auth service

```
{
  "@context": "http://iiif.io/api/image/2/context.json", 
  "@id": "http://image-base-url",    <- same as if auth'z
  "height": 0,        <- or could be real height, or any junk
  "width": 0,         <- or could be real width, or any junk
  "profile": [
    "http://iiif.io/api/image/2/level1.json"
  ], 
  "protocol": "http://iiif.io/api/image", 
  "service": {
    "@context": "http://iiif.io/auth/2/context.json",
    "auth": "http://go-here-to-auth",
    ...maybe more in here...
  }
}
```

**Comment by jpstroop** [comment]
Another idea, which I sort of like: With the introduction of the `sizes` key in info.json, we have a mechanism for indicating what sizes are available, which indirectly suggests (and could be made explicit in a minor release) that the `width` and `height` keys are only there to help you do calculations that require you to know the aspect ratio, and have nothing to do with what you can actually get. I can imagine a client being able to use the aspect ratio to draw an appropriately sized `<div><p>Access Forbidden</p></div>` on the page to stand in for an image in a page turner. So: 

```javascript
{
  "@context": "http://iiif.io/api/image/2/context.json", 
  "@id": "http://image-base-url", // Same as if auth'zed for this URI
  "height": 5720,
  "width": 4628,
  "sizes": [ ], // BUT NO SIZES FOR YOU!
  "profile": [
    "http://iiif.io/api/image/2/level2.json" // Also same as if auth'zed for this URI, right?
  ], 
  "protocol": "http://iiif.io/api/image", 
  "service": {
    "@context": "http://iiif.io/auth/2/context.json",
    "auth": "http://go-here-to-auth"
  }
}
```

If that doesn't fly, I like something more along the lines of *#*2 above as the [semantics of `info.json`](http://iiif.io/api/image/2.0/#information-request) don't change at all--all of the required keys are there. `null` would be slightly better for the dimensions, but we say they must be integers so...

Argument against width/height `0`: I can imagine a lazy Javascript hacker trying to take a shortcut and just saying "`height` is 0, I must need to auth" rather than checking the status code, which could lead to problems. But those problems wouldn't be ours, so maybe it's not a problem :facepunch:.

**Comment by azaroth42** [comment]
I like it. Explicitly empty available sizes with the full h and w for calculating offsets and positioning.

[sinking feeling strikes]

Or I did like it until I checked the context, which says that sizes is iiif:hasSize that takes a resource.  So an empty sizes would be an error given the current JSON / RDF mapping :(  It would need to be changed to take an rdf:List instead so that the list can be empty.

Is that a breaking change, and hence 3.0?  Or is it background magic that we can change in a minor release?

**Comment by jpstroop** [comment]
> Or I did like it until I checked the context, which says that sizes is iiif:hasSize that takes a resource.

Hmm. I _suppose_ it is _technically_ a breaking change, but is there a way we could loosen the context so that either is fine? Why did we choose a resource over a list in the first place? In practice I don't think anyone will care, but we should probably follow our own rules.

**Comment by zimeon** [comment]
I suppose one could have: `"sizes": [ {"width" : 0, "height" : 0} ]` but that seems to be going too far...

Having the maybe or maybe-not breaking change of empty sizes is clean. However, following the logic of Jon's comment of "I can imagine a lazy Javascript hacker trying to take a shortcut and just saying "height is 0, I must need to auth""  ... aren't we just making a more complicated way of doing that? We would be introducing new semantics with this use of `sizes` for no real purpose (since the 401 code is the real thing to say "you need auth, look for the auth service info"). One could piggyback on level0 compliance and `tiles` with empty `scaleFactors` to say nothing is available but this too seems overly complex.

I see the possible benefit of knowing full size or ratio so I go back to a version of my original option #2 with a recommendation to include `height` and `width` as my preference.

**Comment by jpstroop** [comment]
I'm not completely following.

>  "I can imagine a lazy Javascript hacker trying to take a shortcut and just saying "height is 0, I must need to auth"" ... aren't we just making a more complicated way of doing that?

If a lazy programmer does that, I don't think it's our problem. You need to check the HTTP status; if you make an assumption based on something else, that's not our problem. This doesn't bother me. (As indicated by the :facepunch: earlier. :wink:)

> I see the possible benefit of knowing full size or ratio so I go back to a version of my original option #2 with a recommendation to include height and width as my preference.

I'm OK with what you have in *#*2 above, but with the real width and height included. I like the `sizes` idea more since I sorta feel like that's why it's there in the first place, but if we think this is a breaking change, then this is fine w/ me.

**Comment by azaroth42** [comment]
The JSON-LD playground for empty sizes:
  http://tinyurl.com/p5doo6l

Which looks fine in regular JSON mode, but look at ntriples -- there's nothing there.
So if you were running off a triplestore at the back end, you simply couldn't create the right output, regardless of framing or anything else.

Compare with having an entry in the list:
  http://tinyurl.com/oelu9b9

So I don't think that it's possible to have a punning property that sometimes takes an rdf:List and sometimes takes a series of instances.

**Comment by azaroth42** [comment]
+1 to #2 with real sizes. The status code and the existence of the auth service should be sufficient.  And if not, then the client will quickly find out that they need to auth anyway!

**Comment by jpstroop** [comment]
Yup, so it must be!

**Comment by jpstroop** [comment]
Progress!

**Comment by zimeon** [comment]
OK, to recap consensus for easy reference: null `info.json` looks like:

```javascript
{
  "@context": "http://iiif.io/api/image/2/context.json", 
  "@id": "http://image-base-url", // Same as if auth'zed for this URI
  "height": 5720,
  "width": 4628,
  "profile": [
    "http://iiif.io/api/image/2/level2.json" // Same as if auth'zed for this URI
  ], 
  "protocol": "http://iiif.io/api/image", 
  "service": {
    "@context": "http://iiif.io/auth/2/context.json",
    "auth": "http://go-here-to-auth" // URI client should link to for user to auth'n
  }
}
```

**Comment by azaroth42** [comment]
s/"auth":/"@id":/

But yes, the full info.json with a 401 status and a service that has the auth context (whatever that ends up as)

**Comment by jpstroop** [comment]
*could* `sizes` or `tiles` etc be in there? Or other elements of the `profile` (`supports`, `qualities`, `formats`) or does that not make sense since you can't get them until you've auth'd?

**Comment by zimeon** [comment]
...ok, too hasty close.

@azaroth42 - I remember thinking about the question of 'auth' vs. '@id' and concluding for myself that the semantics of @id didn't seem right, but I can't remember why now...

@jpstroop - I think the rule should be that the server may include any other elements from the auth'zed response but that it MUST include the minimal set and the SHOULD be the same values as if auth'zed

**Comment by jpstroop** [comment]
> I think the rule should be that the server may include any other elements from the auth'zed response but that it MUST include the minimal set and the SHOULD be the same values as if auth'zed

Agree

**Comment by azaroth42** [comment]
+1 to SHOULD on the same values as if auth'd.

And my rationale for @id is it's the URI of the authentication service, in the same way that the @id for the image API is the image service, etc.

**Comment by zimeon** [comment]
Now I see why I went for `auth`, in <http://iiif.io/api/annex/services/#requirements> we say:

> Services should have an '@id' that can be dereferenced, and if so, the representation retrieved from that URI should be JSON-LD.

**Comment by azaroth42** [comment]
What about non JSON-LD services? I thought that's why we went with SHOULD for json-ld because there's situations like this when you really do need to point to arbitrary things for the user to interact with outside of our scope.

Similarly, I could imagine putting into the presentation API a link to a DZI "service" if that existed, and they hadn't yet found the true light and implemented IIIF instead.  The DZI isn't an image, you need to know the "protocol" to get to the image tiles... the xml description seems like the equivalent of our info.json.

**Comment by zimeon** [comment]
I agree that your interpretation seems better and more flexible, and that `@id` makes a ton of sense for this case too. So perhaps we just tweak that wording to be a little weaker? Perhaps, something along the lines of:

> Services should have an '@id' that can be dereferenced, and where the representation retrieved from that URI is additional service information, it should be JSON-LD.

(I don't really like the phrase "service information" but can't think how to say "more metadata designed to be consumed by the IIIF client"...)

**Comment by azaroth42** [comment]
Closed in publication of auth spec.
